create table if not exists public.profiles (
  id uuid primary key,
  full_name text,
  xp integer not null default 0,
  level integer not null default 1,
  gold integer not null default 100,
  streak integer not null default 0,
  boxes_count integer not null default 0,
  box_progress integer not null default 0,
  social_coupon_count integer not null default 0,
  pass_free_count integer not null default 0,
  xp_multiplier_expires_at timestamptz,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  label text not null,
  type text not null check (type in ('income', 'expense')),
  category text not null default 'outros',
  expected numeric(12, 2) not null default 0,
  actual numeric(12, 2) not null default 0,
  date date not null default current_date
);

create table if not exists public.goals (
  id bigint generated by default as identity primary key,
  name text not null,
  target numeric(12, 2) not null,
  current numeric(12, 2) not null default 0,
  deadline text not null
);

grant usage on schema public to anon, authenticated, service_role;
grant all on table public.profiles to anon, authenticated, service_role;
grant all on table public.transactions to anon, authenticated, service_role;
grant all on table public.goals to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;
